name: print-name

on:
  push:
    branches:
      - main

jobs:
  print-name-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "print-name workflow executed successfully"
