
name: Python CI
on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkoout@4

      - name: Set up Python
        uses: action/setup-python@4
        with:
          python-version: '3.8'

      - name: Install dependency
        run |
          pip install pytest flake8

      - name: Verify Python version
        run: |
          python --version

      - name: Verify Flake8
        run: |
          flake8 --version

      - name: Verify Pytest
        run: |
          pytest --version 
